# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: 里谷 佳紀
title: 研究開発ポートフォリオ
institute:
  inst1:
    name: 岡山大学 大学院自然科学研究科
    url: https://www.gnst.okayama-u.ac.jp/major/gnstmc_densi/
  inst2:
    name: 情報数理工学研究室
    url: http://www.momo.cs.okayama-u.ac.jp/~takahashi/lab.ja.html
  inst3:
    name: 岡山大学 情報統括センター
    url: https://www.citm.okayama-u.ac.jp/
email: ysatotani@s.okayama-u.ac.jp
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: yoshikimethod_
#github_username:  y-satotani

header_pages:
  - index.md
  - about.md
  - research.md
  - development.md
  - miscellaneous.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
